### ISSUE TITLE
Need script for mariadb ver 5.5

### ISSUE THREAD

**Issue by enggal17** [meob/my2Collector#10]
Hi, Would you share a SQL script for MariaDB version 5.5 cause that version did not has tables performance_schema.global_status, performance_schema.events_statements_summary_global_by_event_name, and performance_schema.replication_connection_status.

Thank you

**Comment by enggal17** [comment]
I got an error below after created m2.db
![image](https://user-images.githubusercontent.com/52996025/99910191-4896a380-2d1f-11eb-899b-9e07aa383617.png)

**Comment by meob** [comment]
Did You tried the MariaDB version of the dashboard?

You can find it here: https://grafana.com/grafana/dashboards/11679

**Comment by meob** [comment]
Did You try the MariaDB version of the dashboard?
There are many little differences between MySQL and MariaDB for DBAs queries...

You can find it here: https://grafana.com/grafana/dashboards/11679

**Comment by meob** [comment]
Have You tried the MariaDB version of the dashboard yet?
There are many little differences between MySQL and MariaDB for DBAs queries...

You can find it here: https://grafana.com/grafana/dashboards/11679

**Comment by enggal17** [comment]
Hi Thanks for your help, but any change in file my2.sql ?
