### ISSUE TITLE
automatic creation does not work for me - 8.0

### ISSUE THREAD

**Issue by tluyben** [meob/my2Collector#11]
When I just run the import of my2.sql I get GLOBAL_STATUS does not exist on line 37; when I manually remove both else statements completely, all works fine.

**Comment by meob** [comment]
Well done.

Did You tested also the script in https://github.com/meob/my2Collector/blob/master/my2_80.sql ?
The main difference are the lines You removed!

**Comment by tluyben** [comment]
Ow! Apologies! I thought because the if is there, it would do that automatically. Thanks for the good work!
