### ISSUE TITLE
ERROR 1061 (42000) at line 26: Duplicate key name 'idx01'

### ISSUE THREAD

**Issue by strikingraghu** [meob/my2Collector#12]
Hi,

Thanks for building this wonderful dashboard content.
While executing below script, I am seeing below error. Can you check this again?
ERROR 1061 (42000) at line 26: Duplicate key name 'idx01'

Thanks,
Raghavendra Guttur

**Comment by meob** [comment]
Hi,

maybe You executed the script twice.
I use the "IF NOT EXISTS" clause for tables but... it does not exist for indexes in MySQL!
(as far as I know it works with MariaDB but I try to use the same script when it is possible)

If You executed the script twice You can ignore the error.

**Comment by strikingraghu** [comment]
Yes, I did execute the script twice and might be the reason for this error!
Let me ignore. Thanks for your speedy response.

**Comment by strikingraghu** [comment]
Yes, I did execute the script twice and might be the reason for this error!
Let me ignore. Thanks for your speedy response.

**Comment by lodhi5580** [comment]
i'm doing this but their is something went wrong and give error duplicate key

**Comment by meob** [comment]
idx01 is a unique KEY (VARIABLE_NAME,timest,host):
it seems You are inserting the same information twice.
The most common cause is executing the script twice:
in this case You can ignore the error.

An other possible is changing host date.
Can be solved deleting/truncating the my2.status table

**Comment by duke-22-01** [comment]
> idx01 is a unique KEY (VARIABLE_NAME,timest,host): it seems You are inserting the same information twice. The most common cause is executing the script twice: in this case You can ignore the error.
> 
> An other possible is changing host date. Can be solved deleting/truncating the my2.status table

Hi am facing same issue can you please guide with the steps how to fix this for below issue:

ERROR 1061 (42000) at line 27: Duplicate key name 'idx01'
