### ISSUE TITLE
How to get real-time data on graphs.

### ISSUE THREAD

**Issue by enggal17** [meob/my2Collector#13]
Hi, how to get real-time data on graphs. If now at 9 am, it has a gap time of about 6 hours.

![image](https://user-images.githubusercontent.com/52996025/105651799-6aaccd80-5eea-11eb-89d8-14408e91e305.png)

**Comment by meob** [comment]
The collector gets real time statitistics (it simply uses set a=now(); ).

The problem maybe related to the timezone...
Are You using the last Grafana version, with the last dashboard version?

You can easly change Grafana timezone settings in the dashboard setting menu:
<img width="489" alt="Screenshot 2021-01-29 at 8 07 05 AM" src="https://user-images.githubusercontent.com/5684349/106243303-6db8fe00-6209-11eb-8a41-351c3ef590a3.png">

**Comment by enggal17** [comment]
Hi, it is worked and thank you

**Comment by meob** [comment]
:-)
