### ISSUE TITLE
Events and Procedures are not found after upgrade application 

### ISSUE THREAD

**Issue by enggal17** [meob/my2Collector#14]
Hi,

I upgraded the application on my VM and suddenly the DB monitor doesn't work, I checked the events, and procedures are not found in my2 DB. Can you help me with how to fix it?

![image](https://user-images.githubusercontent.com/52996025/111078468-1c9a6a80-8528-11eb-9e70-f2f525037758.png)

Thank you

**Comment by enggal17** [comment]
Hi, would you like to provide my2.db for MariaDB version 10.5?

**Comment by meob** [comment]
The same script is expected to work
