### ISSUE TITLE
How to set enabled events without phpmyadmin

### ISSUE THREAD

**Issue by enggal17** [meob/my2Collector#15]
Hi, how to set enabled status on events without PHPMyAdmin

![image](https://user-images.githubusercontent.com/52996025/112187179-74c22280-8c34-11eb-84aa-9beef1f8ccf8.png)

Thank you

**Comment by meob** [comment]
It is a standard MySQL command:
   ALTER EVENT my2.collect_stats ENABLE;

It's documented here:
  https://dev.mysql.com/doc/refman/5.7/en/alter-event.html

**Comment by meob** [comment]
Can be closed...
