### ISSUE TITLE
Some dashboard not shown after upgrade Grafana ver 8

### ISSUE THREAD

**Issue by enggal17** [meob/my2Collector#16]
Hi, I have an issue with the dashboard when upgrading grafana version 8. the issue for Heatmap and Custom Statistic dashboard

![Screenshot_34](https://user-images.githubusercontent.com/52996025/131251474-4dbc0a9a-b9ad-4ae3-8372-b3fa597a8353.jpg)

Is there any update for the script or this method can not work for grafana version 8.  

Thanks

**Comment by meob** [comment]
Grafana 8 has some little differences. I updated a new revision of the dashboard to fix the problem.
You can download it from the Grafana portal:
  https://grafana.com/grafana/dashboards/7991

Thank You for your advice

**Comment by enggal17** [comment]
Thanks but if I want to move to another DB report seem to get a pop-up error in the right and what does it mean. is it ok?

![image](https://user-images.githubusercontent.com/52996025/131416663-2d34d491-62b2-4eba-afe1-b2b0845a084b.png)
