### ISSUE TITLE
No value on custom statistic

### ISSUE THREAD

**Issue by enggal17** [meob/my2Collector#18]
Hi Meob,

I have a question about the custom statistic graph, before the graph was shown the value but now is 0. is it normal?

Thanks

![image](https://user-images.githubusercontent.com/52996025/162657064-439f1356-3fbb-4ef0-bdbe-b24feec1ba0d.png)

**Comment by meob** [comment]
Hi Engal,

ABORTED_CLIENTS can be =0 while SIZEDB generally is not, but the time interval is very short
and maybe that SIZEDB value was set before 8:50... so it can be normal that the Custom Statistics graph is 0.

Try with different time intervals (eg. Last 7 days) or with different custom statistics:
it should work.

meo

**Comment by enggal17** [comment]
Hi Meo, thanks and it is worked now

**Comment by meob** [comment]
Cool!
