### ISSUE TITLE
Syntax error on mysql 8.4

### ISSUE THREAD

**Issue by johndodev** [meob/my2Collector#19]
Hello, 

I tried to install the collector on a mysql 8.4.2 instance and I had a syntax error. Tryed with m2.sql as well. 

After some research I just had to update the DELIMITER sets 
from 
`DELIMITER // ;`
to 
`DELIMITER //`

(and also the reversed ones).

I don't know about mysql 8.0 but I had it on https://dev.mysql.com/doc/refman/8.4/en/stored-programs-defining.html 
(seems same on 8.0).

I can make a PR but I find strange than nobody had the problem ?

**Comment by meob** [comment]
Hi,

maybe the culprit is the client tool You used. The syntax should work with the standard mysql command line client.
Maybe You used a different client like DBeaver that does note require the semicolon.

**Comment by johndodev** [comment]
I was using PMA (copy past or import file). I concede it's not particulary pro. Anyways, if you're cool with that, I have no particuar problems, thanks !
