### ISSUE TITLE
my2 stops collecting after server restart....

### ISSUE THREAD

**Issue by waardd** [meob/my2Collector#3]
It looks like my2 is no longer getting infromation anymore after a restart off the machine.
RHEL updates had caused a reboot of the machine and since then there is no new my2 data

**Comment by meob** [comment]
Did You added the following directive to the my.cnf?
   event_scheduler=1
This way the MySQL scheduler will restart even after a reboot.

You can start the scheduler with the following mysql command:
set global event_scheduler=1;
