### ISSUE TITLE
my2 import of my2.sql

### ISSUE THREAD

**Issue by ZtefanP** [meob/my2Collector#4]
Hi, 

im kind of new to this but im trying to import the my2.sql file and gets error in the import. Tryed with the flat text and with the sql file.

DECLARE a datetime;
DECLARE v varchar(10);

is the part is stops regard the import.

Error from phpmyadmin, and i have tryed heidisql.

# 1064 - You have something wrong with your syntax close ';
CREATE PROCEDURE collect_stats ()
BEGIN
DECLARE and datetime;
DECLARE v varch 'in row 1

//Stefan

**Comment by meob** [comment]
The script should be executed with the mysql command line client...

You can also execute it step by step in the "SQL tab" in phpMyAdmin but You have to change the delimiter when You import the stored procedures:
<img width="320" alt="Screenshot 2020-01-31 at 21 25 52 PM" src="https://user-images.githubusercontent.com/5684349/73572156-659c7600-4470-11ea-9676-b84d8d162dfe.png">

**Comment by ZtefanP** [comment]
Ok, my dumass didnt understand that xD 

Thx alot, will try ! :)

**Comment by ZtefanP** [comment]
Now i get Error 1146: Table 'performance_schema.global_status' doesn't exist, when i import the dashboard on grafana.

**Comment by meob** [comment]
Maybe You are using an old MySQL version (eg. 5.6) or MariaDB:
they both use information_schema.global_status instead of performance_schema.global_status...
It is a small difference but it is annoying: I think I'll pubblish and other dashboard for MariaDB!

**Comment by ZtefanP** [comment]
Ah, yea correct im using MariaDB. Okey, then i know there is no problem with the import then.  Tanks alot for the help

**Comment by meob** [comment]
Try this dashboard:
https://grafana.com/grafana/dashboards/11679

**Comment by ZtefanP** [comment]
That one works even better :D Thx
