### ISSUE TITLE
Table 'performance_schema.global_status' doesn't exist

### ISSUE THREAD

**Issue by moeinrahimi** [meob/my2Collector#5]
after importing my2 dashboard on grafana i get this err message on page load and nothing works.
I imported my2.sql with no issue. and also created a new datasource for my2 database with my2 user.
![image](https://user-images.githubusercontent.com/13715024/77655271-cd160400-6f8f-11ea-97ac-0a1a3f141953.png)
my mysql info: mysql  Ver 15.1 Distrib 10.1.44-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

**Comment by molekm** [comment]
Same issue here.

**Comment by AMASTRO00** [comment]
in variable dashboard (MyVar2) replace with : 

select concat('MySQL version: ',version(), '   Created at: ', date_format(min(create_time),'%Y-%m-%d %T') ,
  '  Started at: ', date_format(date_sub(now(), INTERVAL variable_value second),'%Y-%m-%d %T')) info
  from   information_schema.tables,information_schema.global_status
 where variable_name='UPTIME'
 group by variable_value

Global_status table is contained information_schema and not in performance_schema. 

The same problem is in the my2.sql. 
Try to use an editor and replace all performance_schema.global_status with information_schema.global_status. Good luck

**Comment by meob** [comment]
> Global_status table is contained information_schema and not in performance_schema.
> The same problem is in the my2.sql.
> Try to use an editor and replace all performance_schema.global_status with information_schema.global_status. Good luck

MySQL 5.7 and 8.0 use performance_schema while older MySQL versions and MariaDB use information_schema. my2.sql code tries to use the right schema for the running version but it is not bullet proof. For Grafana dashboards I have 2 different versions... maybe I'll do the same for the my2 collector. Which fork and version are You using?

**Comment by meob** [comment]
Grafana dashboards for MySQL and MariaDB are different

**Comment by QuijoteShin** [comment]
I'm adding extra information to deal with the missing table.

First check where the table actually is. It may be at information_schema or performance_schema.
run this query to know where:
`select TABLE_SCHEMA , TABLE_NAME from information_schema.TABLES t 
where TABLE_NAME ='global_status'`

Also you may enable performance schema at my.conf or mysqld.conf
[mysqld]
performance_schema=ON
