### ISSUE TITLE
[Question] Increase logging frequency

### ISSUE THREAD

**Issue by RAYs3T** [meob/my2Collector#8]
Looks awesome so far!

Only issue for me is that you can't really see the "current" state of the database. So for example if you have lots of new connections you might only see these after 10 minutes in the dashboard.

You think there are any issues with changing the execution time to something lower (like a minute or even every 10 seconds)?
Of course it would consume more storage, but besides that?

**Comment by meob** [comment]
This script is for collecting some useful statistics,
for real time monitoring I prefer tools like Workbench and many others
(eg. telegraf+InfluxDB+Grafana).

The main problem is that You can increase the frequence
but You increase the storage used *and* the database load too.

Sometimes I use a 1 minute interval (eg. during application test)
but I prefer 10 minute interval (like sar tool for instance).

**Comment by narongwate-scm** [comment]
> This script is for collecting some useful statistics,
> for real time monitoring I prefer tools like Workbench and many others
> (eg. telegraf+InfluxDB+Grafana).
> 
> The main problem is that You can increase the frequence
> but You increase the storage used _and_ the database load too.
> 
> Sometimes I use a 1 minute interval (eg. during application test)
> but I prefer 10 minute interval (like sar tool for instance).

I agreed with this. In developer mode, if I want to change the time to 1 minute for proving something.
Where the point to change?

Thanks.

**Comment by RAYs3T** [comment]
@narongwate-scm Its specified in the event that is scheduled you can edit it directly in the db.
Or change it in the script: https://github.com/meob/my2Collector/blob/master/my2.sql#L182

**Comment by meob** [comment]
I do confirm!
