### ISSUE TITLE
Can't run the my2.sql

### ISSUE THREAD

**Issue by csib** [meob/my2Collector#9]
The error is:
#1064 - A Szintaktikai hiba a ';
CREATE PROCEDURE collect_stats()
BEGIN
DECLARE a datetime;
DECLARE v va...'-hez kozeli a 1 sorban

I had run this through phpmyadmin's SQL interface.

The server is: 10.5.5-MariaDB

**Comment by meob** [comment]
If You use phpMyAdmin to create a MySQL stored procedure You have to change the delimiter:

<img width="650" alt="Screenshot 2020-09-29 at 7 42 40 AM" src="https://user-images.githubusercontent.com/5684349/94517062-77b0fd00-0227-11eb-992e-4448e964fda2.png">

MariaDB 10.5 should be fine, I'll test it againg.

**Comment by meob** [comment]
phpMyAdmin can be used to create procedures but the delimiter must be defined correctly
